import '../models/letter_tile.dart';

abstract interface class WordDictionary {
  bool contains(String word);
}

class EmbeddedWordDictionary implements WordDictionary {
  const EmbeddedWordDictionary();

  static final Set<String> _words = {
    'age', 'aid', 'air', 'ale', 'all', 'and', 'ant', 'any',
    'arc', 'arm', 'art', 'ash', 'ask', 'axe', 'bad', 'bag',
    'ban', 'bar', 'bat', 'bay', 'bed', 'bee', 'bet', 'bid',
    'big', 'bit', 'bow', 'box', 'boy', 'bud', 'bug', 'bun',
    'bus', 'but', 'buy', 'can', 'cap', 'car', 'cat', 'cop',
    'cow', 'cry', 'cup', 'cut', 'dam', 'day', 'den', 'dig',
    'dim', 'dog', 'dot', 'dry', 'due', 'dug', 'ear', 'eat',
    'egg', 'end', 'era', 'eve', 'eye', 'fan', 'far', 'fat',
    'fee', 'few', 'fig', 'fin', 'fit', 'fix', 'flu', 'fly',
    'fog', 'for', 'fox', 'fry', 'fun', 'fur', 'gap', 'gas',
    'gem', 'get', 'god', 'got', 'gun', 'guy', 'gym', 'hat',
    'her', 'hex', 'hid', 'hip', 'his', 'hit', 'hop', 'hot',
    'hue', 'hug', 'hut', 'ice', 'ill', 'ink', 'ion', 'ivy',
    'jab', 'jam', 'jar', 'jaw', 'jet', 'job', 'jog', 'joy',
    'key', 'kid', 'kin', 'lab', 'lap', 'law', 'lay', 'led',
    'leg', 'let', 'lid', 'lie', 'lip', 'lit', 'log', 'lot',
    'low', 'mad', 'man', 'map', 'mat', 'may', 'men', 'met',
    'mix', 'mob', 'mud', 'mug', 'nap', 'net', 'new', 'nod',
    'nor', 'not', 'now', 'nut', 'oak', 'odd', 'off', 'oil',
    'old', 'one', 'orb', 'ore', 'our', 'out', 'owl', 'own',
    'pad', 'pan', 'par', 'pat', 'paw', 'pay', 'pen', 'pet',
    'pie', 'pig', 'pin', 'pit', 'pot', 'pub', 'pup', 'rag',
    'ram', 'ran', 'rat', 'raw', 'ray', 'red', 'rib', 'rid',
    'rig', 'rim', 'rip', 'rob', 'rod', 'rot', 'row', 'rub',
    'rug', 'run', 'sad', 'sap', 'sat', 'saw', 'say', 'sea',
    'set', 'sew', 'she', 'shy', 'sin', 'sip', 'sir', 'sit',
    'six', 'sky', 'sly', 'sob', 'son', 'sow', 'spy', 'sun',
    'tab', 'tag', 'tan', 'tap', 'tar', 'tax', 'tea', 'ten',
    'the', 'tie', 'tin', 'tip', 'toe', 'ton', 'too', 'top',
    'toy', 'try', 'tub', 'two', 'use', 'van', 'vat', 'vet',
    'via', 'vow', 'war', 'was', 'wax', 'way', 'web', 'wed',
    'wet', 'who', 'why', 'wig', 'win', 'wit', 'wolf', 'won',
    'wow', 'yes', 'yet', 'you', 'zip', 'zoo', 'able', 'acid',
    'aged', 'ally', 'also', 'ache', 'atom', 'aunt', 'auto', 'away',
    'axis', 'bake', 'bald', 'ball', 'band', 'bank', 'bare', 'bark',
    'barn', 'base', 'bath', 'bead', 'beak', 'beam', 'bean', 'bear',
    'beat', 'beef', 'been', 'beer', 'bell', 'belt', 'bend', 'bent',
    'best', 'bike', 'bind', 'bird', 'bite', 'blow', 'blue', 'blur',
    'boat', 'body', 'boil', 'bold', 'bolt', 'bomb', 'bond', 'bone',
    'book', 'boom', 'boot', 'bore', 'born', 'boss', 'both', 'bowl',
    'bran', 'brew', 'brow', 'burn', 'bury', 'bush', 'busy', 'byte',
    'cage', 'cake', 'calf', 'call', 'calm', 'came', 'camp', 'cane',
    'cape', 'card', 'care', 'cart', 'case', 'cash', 'cast', 'cave',
    'cell', 'chip', 'chop', 'city', 'clap', 'claw', 'clay', 'clip',
    'club', 'clue', 'coal', 'coat', 'code', 'coil', 'coin', 'cold',
    'come', 'cone', 'cook', 'cool', 'cope', 'copy', 'cord', 'core',
    'cork', 'corn', 'cost', 'crab', 'crew', 'crop', 'crow', 'cure',
    'curl', 'cute', 'dame', 'damp', 'dare', 'dark', 'dart', 'dash',
    'data', 'date', 'dawn', 'dead', 'deal', 'dear', 'debt', 'deck',
    'deed', 'deep', 'deer', 'demo', 'dial', 'dice', 'diet', 'dime',
    'dine', 'dirt', 'dish', 'dive', 'dock', 'does', 'dome', 'done',
    'doom', 'door', 'dose', 'dove', 'down', 'drag', 'draw', 'drew',
    'drip', 'drop', 'drug', 'drum', 'dual', 'duck', 'dull', 'dune',
    'dusk', 'dust', 'duty', 'each', 'earn', 'ease', 'east', 'easy',
    'edge', 'edit', 'else', 'even', 'ever', 'evil', 'exam', 'exit',
    'face', 'fact', 'fade', 'fail', 'fair', 'fake', 'fall', 'fame',
    'fang', 'fare', 'farm', 'fast', 'fate', 'fear', 'feat', 'feed',
    'feel', 'feet', 'fell', 'felt', 'fern', 'file', 'fill', 'film',
    'find', 'fine', 'fire', 'firm', 'fish', 'fist', 'five', 'flag',
    'flame', 'flap', 'flat', 'flaw', 'flee', 'flew', 'flex', 'flip',
    'flow', 'foam', 'foil', 'fold', 'folk', 'font', 'food', 'fool',
    'foot', 'ford', 'fork', 'form', 'fort', 'foul', 'four', 'free',
    'frog', 'from', 'fuel', 'full', 'fume', 'fund', 'fury', 'fuse',
    'fuss', 'gain', 'gale', 'game', 'gang', 'gate', 'gave', 'gaze',
    'gear', 'gene', 'gift', 'girl', 'give', 'glad', 'glow', 'glue',
    'goal', 'goat', 'gold', 'golf', 'gone', 'good', 'gown', 'grab',
    'gray', 'grew', 'grey', 'grid', 'grim', 'grin', 'grip', 'grow',
    'gulf', 'gulp', 'gust', 'hail', 'hair', 'half', 'hall', 'halt',
    'hand', 'hang', 'hard', 'harm', 'hate', 'have', 'hawk', 'haze',
    'head', 'heal', 'heap', 'hear', 'heat', 'heel', 'heir', 'held',
    'hell', 'helm', 'help', 'herb', 'herd', 'here', 'hero', 'hide',
    'high', 'hike', 'hill', 'hint', 'hire', 'hive', 'hold', 'hole',
    'holy', 'home', 'hood', 'hoof', 'hook', 'hope', 'horn', 'hose',
    'host', 'hour', 'howl', 'huge', 'hull', 'hunt', 'hurl', 'hurt',
    'hymn', 'iced', 'icon', 'idea', 'idle', 'inch', 'into', 'iron',
    'item', 'jade', 'jazz', 'jeep', 'joke', 'jolt', 'jump', 'june',
    'junk', 'jury', 'just', 'keen', 'keep', 'kelp', 'kept', 'keys',
    'kick', 'kill', 'kind', 'king', 'kiss', 'kite', 'knee', 'knew',
    'knit', 'knot', 'know', 'lace', 'lack', 'lady', 'laid', 'lake',
    'lamb', 'lamp', 'land', 'lane', 'last', 'late', 'lawn', 'lazy',
    'lead', 'leaf', 'leak', 'lean', 'leap', 'left', 'lend', 'lens',
    'less', 'life', 'lift', 'like', 'lime', 'limp', 'line', 'link',
    'lion', 'list', 'live', 'load', 'loaf', 'loan', 'lock', 'loft',
    'logo', 'lone', 'long', 'look', 'loop', 'loose', 'lord', 'lose',
    'loss', 'lost', 'loud', 'love', 'luck', 'lump', 'lung', 'lure',
    'lush', 'lust', 'made', 'magic', 'maid', 'mail', 'main', 'make',
    'male', 'mana', 'many', 'mark', 'mask', 'mass', 'mast', 'mate',
    'maze', 'meal', 'mean', 'meat', 'meet', 'melt', 'mend', 'menu',
    'mere', 'mesh', 'mess', 'mice', 'mild', 'mile', 'milk', 'mind',
    'mine', 'mint', 'miss', 'mist', 'mold', 'mole', 'monk', 'mood',
    'moon', 'moor', 'more', 'moss', 'most', 'moth', 'move', 'much',
    'muse', 'must', 'myth', 'nail', 'name', 'navy', 'near', 'neat',
    'neck', 'need', 'nest', 'news', 'next', 'nice', 'nine', 'node',
    'none', 'noon', 'norm', 'nose', 'note', 'noun', 'nude', 'null',
    'numb', 'oath', 'obey', 'odor', 'omen', 'once', 'only', 'onto',
    'open', 'oral', 'oven', 'over', 'pace', 'pack', 'pact', 'page',
    'paid', 'pain', 'pair', 'pale', 'palm', 'pane', 'park', 'part',
    'pass', 'past', 'path', 'pave', 'peak', 'peal', 'pear', 'peat',
    'peek', 'peel', 'peer', 'pest', 'pick', 'pier', 'pile', 'pill',
    'pine', 'pink', 'pipe', 'pity', 'plan', 'play', 'plot', 'plow',
    'plug', 'plum', 'plus', 'poem', 'poet', 'pole', 'poll', 'pond',
    'pony', 'pool', 'poor', 'pork', 'port', 'pose', 'post', 'pour',
    'pray', 'prey', 'prod', 'prop', 'pull', 'pulp', 'pump', 'pure',
    'push', 'quiz', 'race', 'rack', 'raft', 'rage', 'raid', 'rail',
    'rain', 'rake', 'ramp', 'rang', 'rank', 'rare', 'rash', 'rate',
    'rays', 'read', 'real', 'reed', 'reef', 'reel', 'rent', 'rest',
    'rice', 'rich', 'ride', 'rift', 'ring', 'riot', 'ripe', 'rise',
    'risk', 'road', 'roam', 'roar', 'robe', 'rock', 'rode', 'role',
    'roll', 'roof', 'room', 'root', 'rope', 'rose', 'rosy', 'rove',
    'ruby', 'rude', 'ruin', 'rule', 'rung', 'rush', 'rust', 'safe',
    'sage', 'said', 'sail', 'sake', 'sale', 'salt', 'same', 'sand',
    'sane', 'save', 'scan', 'scar', 'seal', 'seam', 'seat', 'seed',
    'seek', 'seem', 'seen', 'self', 'sell', 'send', 'sent', 'shed',
    'shelf', 'shell', 'shift', 'shin', 'ship', 'shock', 'shoe', 'shone',
    'shoot', 'shop', 'shot', 'show', 'shut', 'sick', 'side', 'sigh',
    'sign', 'silk', 'sing', 'sink', 'site', 'size', 'skew', 'skin',
    'skip', 'skull', 'slab', 'slam', 'slap', 'slid', 'slim', 'slip',
    'slot', 'slow', 'slug', 'smog', 'snap', 'snow', 'soak', 'soap',
    'sock', 'soda', 'sofa', 'soft', 'soil', 'sold', 'sole', 'some',
    'song', 'soon', 'sore', 'sort', 'soul', 'soup', 'sour', 'span',
    'spar', 'spat', 'spawn', 'spell', 'spend', 'spent', 'spin', 'spit',
    'spoil', 'spoke', 'spot', 'spun', 'spur', 'stab', 'stage', 'stain',
    'stair', 'stake', 'stale', 'stall', 'stand', 'star', 'stare', 'stark',
    'start', 'stay', 'steal', 'steam', 'steel', 'steep', 'steer', 'step',
    'stew', 'stick', 'stiff', 'still', 'sting', 'stir', 'stock', 'stole',
    'stone', 'stood', 'stop', 'store', 'storm', 'story', 'stove', 'stray',
    'strike', 'strip', 'stuck', 'study', 'stuff', 'stun', 'such', 'suit',
    'sunk', 'sure', 'surf', 'swam', 'swan', 'swap', 'swarm', 'sway',
    'swear', 'sweat', 'sweep', 'sweet', 'swept', 'swim', 'swing', 'sword',
    'take', 'tale', 'talk', 'tall', 'tame', 'tank', 'tape', 'task',
    'teach', 'team', 'tear', 'tell', 'tend', 'tent', 'term', 'test',
    'text', 'than', 'that', 'them', 'then', 'they', 'thin', 'this',
    'thud', 'thus', 'tide', 'tidy', 'tile', 'till', 'tilt', 'time',
    'tiny', 'toad', 'told', 'toll', 'tomb', 'tone', 'took', 'tool',
    'tore', 'torn', 'toss', 'tour', 'town', 'trap', 'tray', 'tree',
    'trek', 'trend', 'trial', 'tribe', 'trick', 'tried', 'trip', 'true',
    'tuck', 'tune', 'turf', 'turn', 'twin', 'type', 'ugly', 'unfit',
    'unit', 'upon', 'urge', 'used', 'user', 'vain', 'vale', 'vane',
    'vary', 'vase', 'vast', 'veil', 'vein', 'verb', 'very', 'vest',
    'view', 'vine', 'visa', 'void', 'vote', 'wage', 'wail', 'wait',
    'wake', 'walk', 'wall', 'want', 'ward', 'ware', 'warm', 'warn',
    'wars', 'wash', 'wasp', 'wave', 'weak', 'wear', 'weed', 'week',
    'weep', 'weld', 'well', 'went', 'wept', 'were', 'west', 'what',
    'when', 'whip', 'whom', 'wide', 'wife', 'wild', 'will', 'wind',
    'wine', 'wing', 'wink', 'wire', 'wise', 'wish', 'with', 'wood',
    'wool', 'word', 'wore', 'work', 'worm', 'worn', 'wrap', 'yard',
    'yarn', 'year', 'yell', 'yoga', 'yolk', 'your', 'zeal', 'zero',
    'zone', 'attack', 'battle', 'beast', 'blade', 'blast', 'blaze', 'block',
    'blood', 'bonus', 'brave', 'break', 'bring', 'brush', 'build', 'burst',
    'catch', 'chain', 'chant', 'charm', 'chase', 'cheap', 'check', 'chest',
    'chief', 'child', 'chose', 'clash', 'class', 'clean', 'clear', 'climb',
    'cloak', 'close', 'cloth', 'cloud', 'coast', 'combo', 'comet', 'crack',
    'craft', 'crash', 'crawl', 'cream', 'creek', 'creep', 'crest', 'crime',
    'cross', 'crowd', 'crown', 'crush', 'crust', 'curse', 'curve', 'cycle',
    'dance', 'death', 'delay', 'depth', 'devil', 'doubt', 'dozen', 'draft',
    'drain', 'drama', 'dream', 'dress', 'drift', 'drill', 'drive', 'drove',
    'dwarf', 'eagle', 'earth', 'eight', 'elbow', 'elder', 'elite', 'empty',
    'enemy', 'enjoy', 'enter', 'equal', 'error', 'essay', 'event', 'every',
    'exact', 'exile', 'exist', 'fault', 'feast', 'fence', 'fever', 'field',
    'fight', 'final', 'first', 'fixed', 'flash', 'fleet', 'flesh', 'float',
    'flock', 'flood', 'floor', 'flour', 'focus', 'force', 'forge', 'forth',
    'forty', 'found', 'frame', 'fraud', 'fresh', 'front', 'frost', 'fruit',
    'gauge', 'ghost', 'giant', 'glass', 'glide', 'globe', 'glory', 'glove',
    'grace', 'grade', 'grain', 'grand', 'grant', 'grape', 'graph', 'grasp',
    'grass', 'grave', 'great', 'greed', 'green', 'greet', 'grief', 'grind',
    'gross', 'group', 'grove', 'guard', 'guess', 'guest', 'guide', 'guild',
    'habit', 'happy', 'harsh', 'haste', 'haunt', 'heart', 'heavy', 'hedge',
    'honor', 'horse', 'hotel', 'house', 'human', 'humor', 'hurry', 'ideal',
    'image', 'index', 'inner', 'input', 'issue', 'ivory', 'jelly', 'joint',
    'judge', 'juice', 'jumbo', 'knife', 'knock', 'known', 'label', 'labor',
    'large', 'laser', 'latch', 'layer', 'learn', 'least', 'leave', 'level',
    'light', 'limit', 'liver', 'lodge', 'logic', 'lower', 'loyal', 'lucky',
    'lunar', 'lunch', 'major', 'maker', 'march', 'match', 'maybe', 'mayor',
    'medal', 'medium', 'melon', 'merge', 'merry', 'metal', 'meter', 'might',
    'minor', 'minus', 'mirth', 'mirror', 'model', 'moist', 'money', 'month',
    'moral', 'motor', 'mount', 'mouse', 'mouth', 'movie', 'music', 'naval',
    'nerve', 'never', 'newer', 'night', 'noble', 'noise', 'north', 'novel',
    'nurse', 'ocean', 'offer', 'often', 'orbit', 'order', 'organ', 'other',
    'ought', 'outer', 'owner', 'panel', 'panic', 'paper', 'party', 'pause',
    'peace', 'phase', 'phone', 'photo', 'piece', 'pilot', 'pitch', 'place',
    'plain', 'plane', 'plant', 'plate', 'point', 'pound', 'power', 'press',
    'price', 'pride', 'prime', 'print', 'prior', 'prize', 'proof', 'proud',
    'prove', 'pulse', 'punch', 'pupil', 'purse', 'queen', 'query', 'quest',
    'quick', 'quiet', 'quilt', 'quirk', 'quote', 'radar', 'radio', 'raise',
    'rally', 'ranch', 'range', 'rapid', 'ratio', 'reach', 'react', 'realm',
    'rebel', 'refer', 'reign', 'relax', 'reply', 'reset', 'ridge', 'rifle',
    'right', 'rigid', 'risky', 'rival', 'river', 'roast', 'robot', 'rocky',
    'rogue', 'roost', 'rough', 'round', 'route', 'royal', 'rugby', 'ruler',
    'rural', 'sadly', 'salad', 'sauce', 'scale', 'scare', 'scarf', 'scene',
    'scent', 'scold', 'scoop', 'scope', 'score', 'scorn', 'scout', 'scrap',
    'screw', 'sense', 'serve', 'seven', 'shade', 'shake', 'shall', 'shame',
    'shape', 'share', 'shark', 'sharp', 'shave', 'sheep', 'sheer', 'sheet',
    'shelter', 'shield', 'shine', 'shirt', 'shore', 'short', 'shout', 'shove',
    'shown', 'shrub', 'sight', 'silly', 'since', 'sixth', 'sixty', 'skill',
    'slate', 'sleek', 'sleep', 'slept', 'slice', 'slide', 'slime', 'small',
    'smart', 'smash', 'smell', 'smile', 'smoke', 'snake', 'sneak', 'solid',
    'solve', 'sonic', 'sorry', 'sound', 'south', 'space', 'spade', 'spare',
    'spark', 'speak', 'spear', 'speed', 'spice', 'spine', 'spire', 'split',
    'sport', 'spray', 'squad', 'stack', 'staff', 'stalk', 'stamp', 'state',
    'stead', 'steak', 'steed', 'stern', 'strap', 'straw', 'style', 'sugar',
    'suite', 'sunny', 'super', 'surge', 'swamp', 'swift', 'table', 'taken',
    'talon', 'tarot', 'taste', 'thank', 'theft', 'theme', 'there', 'these',
    'thick', 'thief', 'thing', 'think', 'third', 'those', 'three', 'threw',
    'throw', 'thumb', 'tiger', 'tight', 'timer', 'title', 'toast', 'today',
    'token', 'topic', 'torch', 'total', 'touch', 'tough', 'tower', 'toxic',
    'trace', 'track', 'trade', 'trail', 'train', 'trait', 'trash', 'treat',
    'troop', 'trout', 'truce', 'truck', 'trust', 'truth', 'tumor', 'tunic',
    'twice', 'twist', 'ultra', 'uncle', 'under', 'union', 'unity', 'until',
    'upper', 'upset', 'urban', 'usage', 'usual', 'valid', 'value', 'valve',
    'vapor', 'venom', 'venue', 'verse', 'video', 'vigor', 'villa', 'virus',
    'visit', 'vital', 'vivid', 'vocal', 'voice', 'voter', 'wafer', 'wager',
    'wagon', 'waist', 'watch', 'water', 'weary', 'weave', 'wedge', 'weigh',
    'weird', 'wheat', 'wheel', 'where', 'which', 'while', 'white', 'whole',
    'whose', 'widen', 'widow', 'width', 'witch', 'women', 'world', 'worry',
    'worse', 'worst', 'worth', 'would', 'wound', 'woven', 'wreck', 'wrist',
    'write', 'wrong', 'wrote', 'yield', 'young', 'youth', 'ancient', 'archer',
    'armor', 'arrow', 'blazing', 'bless', 'bright', 'brutal', 'burning', 'cannon',
    'castle', 'charge', 'clever', 'combat', 'command', 'conjure', 'crimson', 'critical',
    'crystal', 'curious', 'damage', 'danger', 'defend', 'destroy', 'dragon', 'dungeon',
    'element', 'enchant', 'endless', 'eternal', 'evasion', 'fantasy', 'fearless', 'ferocious',
    'fireball', 'flaming', 'forest', 'fortune', 'freedom', 'furious', 'goblin', 'golden',
    'guardian', 'healing', 'heaven', 'heroic', 'hunter', 'immune', 'impact', 'inferno',
    'justice', 'kingdom', 'knight', 'legend', 'lightning', 'magical', 'mystery', 'mystic',
    'penalty', 'phantom', 'phoenix', 'poison', 'potion', 'protect', 'radiant', 'rampage',
    'reflect', 'resist', 'reverse', 'ritual', 'savage', 'scatter', 'serpent', 'shatter',
    'skeleton', 'sorcery', 'spartan', 'special', 'spirit', 'sprint', 'stealth', 'strange',
    'stretch', 'summon', 'thunder', 'titanic', 'torment', 'trigger', 'triumph', 'valiant',
    'vampire', 'vanish', 'vicious', 'victory', 'villain', 'volcano', 'warrior', 'weapon',
    'wizard', 'wonder',
  };

  @override
  bool contains(String word) => _words.contains(word);
}

class WordValidator {
  WordValidator({WordDictionary? dictionary})
      : _dictionary = dictionary ?? const EmbeddedWordDictionary();

  static const int minimumWordLength = 3;

  final WordDictionary _dictionary;

  bool isValid({required String word, required List<LetterTile> currentHand}) {
    final normalizedWord = word.trim().toUpperCase();
    if (normalizedWord.length < minimumWordLength) return false;
    if (!_dictionary.contains(normalizedWord.toLowerCase())) return false;

    final availableCounts = _letterCounts(
      currentHand.map((tile) => tile.letter),
    );
    final requestedCounts = _letterCounts(normalizedWord.split(''));

    for (final entry in requestedCounts.entries) {
      if ((availableCounts[entry.key] ?? 0) < entry.value) return false;
    }
    return true;
  }

  Map<String, int> _letterCounts(Iterable<String> letters) {
    final counts = <String, int>{};
    for (final letter in letters) {
      final normalizedLetter = letter.toUpperCase();
      counts[normalizedLetter] = (counts[normalizedLetter] ?? 0) + 1;
    }
    return counts;
  }
}